export const authConstant = {
    LOGIN_REQUEST:"LOGIN_REQUEST",
    LOGIN_SUCCESS:"LOGIN_SUCCESS",
    LOGIN_FAILURE:"LOGIN_FAILURE",
    LOGOUT_USER : "LOGOUT_USER",
    LOGOUT_REQUEST:"LOGOUT_REQUEST",
    LOGOUT_SUCCESS:"LOGOUT_SUCCESS",
    LOGOUT_FAILURE:"LOGOUT_FAILURE"
}

export const userConstant = {
    SIGNUP_REQUEST : "SIGNUP_REQUEST",
    SIGNUP_SUCCESS : "SIGNUP_SUCCESS",
    SIGNUP_FAILURE : "SIGNUP_FAILURE"
}